In [80]:
import sys
import numpy as np

### Comparison normal python vs numpy: numpy is lighter and faster!

In [183]:
# size of list in normal python
sys.getsizeof([1])

64

In [82]:
# size of list in numpy
np.array([1]).nbytes

4

### Basic Numpy Arrays

In [83]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [84]:
a = np.array([1,2,3,4])
b = np.array([0,.5,1,1.5,2])

In [85]:
# slicing, return 1st & 2nd element from list a
a[0], a[1]

(1, 2)

In [86]:
# slicing, return 2nd & 3rd element from list a
a[1:3]

array([2, 3])

In [87]:
# slicing from 1st element, skip 2
a[::2]

array([1, 3])

In [88]:
# normal indexing return set
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [89]:
# multi indexing, return numpay array
b[[0, 2, -1]]

array([0., 1., 2.])

### Array Types

In [90]:
a

array([1, 2, 3, 4])

In [91]:
a.dtype

dtype('int32')

In [92]:
b.dtype

dtype('float64')

In [93]:
# change data type integer to float
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [94]:
# There's no point storing char or string in numpy, because numpy only store numbers, dates, & booleans
d = np.array([{'a': 1}, sys])
d.dtype

dtype('O')

### Dimensions and Shapes

In [95]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [96]:
# multi dimentional array A, has 2 rows & 3 columns
A.shape

(2, 3)

In [97]:
# multi dimentional array A, has 2 dimensions: 1 vertical & 1 horizontal, or can refer to shape
A.ndim

2

In [98]:
# multi dimentional array A, has size = 6: total number of elements
A.size

6

In [99]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [100]:
# multi dimentional array B, has 2 lists, each 2 rows & 3 columns
B.shape

(2, 2, 3)

In [101]:
# multi dimentional array B has 3 dimentions: can refer to shape
B.ndim

3

In [102]:
# multi dimentional array B, has size = 12: total number of elements
B.size

12

If the shpae isn't consistent, it'll just fall back to regular python objects:

In [103]:
C = np.array([
    [
        [12,11,18],
        [9,8,7]
    ],
    [
        [6,5,4]
    ]
])

In [104]:
C.dtype

dtype('O')

In [105]:
C.shape

(2,)

In [106]:
C.size

2

### Indexing and Slicing of Matrices

In [107]:
# square matrix
A = np.array([
#    0.1.2.
    [1,2,3], # 0
    [4,5,6], # 1
    [7,8,9] # 2
])

In [108]:
# return 2nd row
A[1]

array([4, 5, 6])

In [109]:
# return 2nd row as 1st dimention, and 1st column as the 2nd dimention
A[1, 0]

4

In [110]:
# return row 1 untill row 2 (1st dimention only)
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
# return all rows as 1st dimention, but only 1st & 2nd columns as 2nd dimention
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [112]:
# return row 1 & 2 as 1st dimention, but only column 1 & 2 as the 2nd dimention
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [113]:
# return row 1 & 2 as 1st dimention, but only for column 2 as 2nd dimention
A[:2, 2:]

array([[3],
       [6]])

In [114]:
# assign 10 to all numbers in 2nd row
A[1] = np.array([10, 10, 10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [115]:
# assign 99 to all numbers in 3nd row
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics

In [116]:
a = np.array([1,2,3,4]) 

In [117]:
a.sum()

10

In [118]:
a.mean()

2.5

In [119]:
a.std()

1.118033988749895

In [120]:
a.var()

1.25

In [121]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [122]:
A.sum()

45

In [123]:
A.mean()

5.0

In [124]:
A.std()

2.581988897471611

In [125]:
# return sum of all numbers vertically (1st column, 2nd column, 3rd column)
A.sum(axis=0)

array([12, 15, 18])

In [126]:
# return sum of all numbers horizontally (1st row, 2nd row, 3rd row)
A.sum(axis=1)

array([ 6, 15, 24])

In [127]:
# return mean vertically (1st column, 2nd column, 3rd column)
A.mean(axis=0)

array([4., 5., 6.])

In [128]:
# return mean horizontally (1st row, 2nd row, 3rd row)
A.mean(axis=1)

array([2., 5., 8.])

### Broadcasting and Vectorized Operations

In [129]:
# vectorized operation: apply math operations to all numbers in array
# any operations performed in numpy array will not modified, but it will return a new array

In [130]:
# return 0 to 4
a = np.arange(4)
a

array([0, 1, 2, 3])

In [131]:
# add 10 to all numbers in numpy list a
a + 10

array([10, 11, 12, 13])

In [132]:
# times 10 to all numbers in numpy list a
a * 10

array([ 0, 10, 20, 30])

In [133]:
# add 10 to all numbers in numpy list a and replace the result
a += 10
a

array([10, 11, 12, 13])

In [134]:
l = [0,1,2,3]

In [135]:
# list comprehension. Same goal that can be achieve faster using numpy array
[i * 10 for i in l]

[0, 10, 20, 30]

In [136]:
b = np.array([10,10,10,10])

In [137]:
# list b added to list a per number correspondingly
a + b

array([20, 21, 22, 23])

In [138]:
# list b multiplied to list a per number correspondingly
a * b

array([100, 110, 120, 130])

### Boolean Arrays

In [139]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [140]:
# normal indexing
a[0], a[-1]

(0, 3)

In [141]:
# multi indexing
a[[0, -1]]

array([0, 3])

In [142]:
# the same goal with multi-dimentional indexing above, but using boolean array
a[[True, False, False, True]]

array([0, 3])

In [143]:
# return numbers which >= 2
a >= 2

array([False, False,  True,  True])

In [144]:
# [(a < 1) | (a > 2)] will return boolean array like above
# then a[<boolean arrays>] will return [0, 3]
a[(a < 1) | (a > 2)]

array([0, 3])

In [145]:
a.mean()

1.5

In [146]:
# return numbers on list 'a' that >= mean (1.5)
a[a > a.mean()]

array([2, 3])

In [147]:
# return numbers on list 'a' that IS NOT >= mean (1.5)
a[~(a > a.mean())]

array([0, 1])

In [148]:
# return random 3 dimentions multi-dimentional arrays
A = np.random.randint(100, size=(3,3))
A

array([[80, 28, 59],
       [32, 90, 87],
       [91, 28, 61]])

In [149]:
# return true for numbers that > 5
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [150]:
# return the number for each True value
A[A > 30]

array([80, 59, 32, 90, 87, 91, 61])

### Linear Algebra

In [151]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [152]:
# dot product
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [153]:
# cross product
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [154]:
# matrix transpose
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [155]:
# dot product and cross product
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Useful Numpy function

**random**

In [230]:
np.random.random(size=2)

array([0.86825633, 0.79922359])

In [231]:
np.random.normal(size=2)

array([-0.57586292,  0.88511406])

In [232]:
# return random number of 2 rows & 4 columns matrix
np.random.rand(2, 4)

array([[0.92469248, 0.31917281, 0.70286926, 0.76574818],
       [0.51097931, 0.02749947, 0.50898156, 0.55798048]])

---
**arange**

In [219]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [221]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
**reshape**

In [225]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [226]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
**linspace**

In [240]:
# linespace create an evenly spaced sequence in a specified interval

In [239]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [236]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [245]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
**zeros, ones, empty**

In [321]:
# numpy.zeros: returns a new array of given shape and type, with zeros
# numpy.ones: returns a new array of given shape and type, with ones
# numpy.empty: return a new array of given shape and type, with random values

In [322]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [323]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [324]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [325]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [326]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [327]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [328]:
np.empty(3)

array([1., 1., 1.])

In [329]:
np.empty((2,2))

array([[8.289046e-317, 0.000000e+000],
       [0.000000e+000, 0.000000e+000]])

---
**identity and eye**

In [294]:
# numpy.identity: return a identity matrix i.e. a square matrix with ones on the main diagonal
# numpy.eye: return a matrix having 1’s on the diagonal and 0’s elsewhere w.r.t. k.

In [295]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [296]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [297]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [298]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [299]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])